"""add_incident_correlation_engine

Revision ID: 2771f1ebb7be
Revises: 60a696c5452e
Create Date: 2026-09-16 10:51:33.393554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2771f1ebb7be'
down_revision: Union[str, None] = '60a696c5452e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_device_id_last_seen', 'incidents', ['device_id', 'last_seen'], unique=False)
    op.create_index('ix_incidents_severity', 'incidents', ['severity'], unique=False)
    op.create_index('ix_incidents_status', 'incidents', ['status'], unique=False)

    # MUHIM: SQLite ALTER TABLE orqali constraint (FK) qo'shishni
    # QO'LLAB-QUVVATLAMAYDI (faqat PostgreSQL'da to'g'ridan-to'g'ri
    # ishlaydi) - `batch_alter_table` orqali har ikkala dialektda ham
    # to'g'ri ishlaydigan (SQLite'da nusxa-va-almashtirish strategiyasi,
    # PostgreSQL'da oddiy ALTER) yagona kod yo'li ishlatiladi. Autogenerate
    # constraint nomini avtomatik bermagani uchun ("None") aniq nom
    # qo'shildi - aks holda downgrade() uni nom bo'yicha topa olmasdi.
    with op.batch_alter_table('alerts') as batch_op:
        batch_op.add_column(sa.Column('incident_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_alerts_incident_id', ['incident_id'], unique=False)
        batch_op.create_foreign_key('fk_alerts_incident_id', 'incidents', ['incident_id'], ['id'])


def downgrade() -> None:
    with op.batch_alter_table('alerts') as batch_op:
        batch_op.drop_constraint('fk_alerts_incident_id', type_='foreignkey')
        batch_op.drop_index('ix_alerts_incident_id')
        batch_op.drop_column('incident_id')

    op.drop_index('ix_incidents_status', table_name='incidents')
    op.drop_index('ix_incidents_severity', table_name='incidents')
    op.drop_index('ix_incidents_device_id_last_seen', table_name='incidents')
    op.drop_table('incidents')
