"""add_network_response_done_and_device_file_path

Revision ID: 33ec5a1ac904
Revises: 2771f1ebb7be
Create Date: 2026-09-16 12:13:19.260788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ec5a1ac904'
down_revision: Union[str, None] = '2771f1ebb7be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('network_response_done', sa.Boolean(), nullable=True))
    op.add_column('file_events', sa.Column('device_file_path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###

    # MUHIM: mavjud (production'dagi) qatorlarda bu ustun endi
    # ADD COLUMN'dan keyin NULL bo'ladi - response_engine.py'ning
    # `network_response_done.is_(False)` so'rovi buni allaqachon
    # `or_(is_(None), is_(False))` bilan xavfsiz boshqaradi, lekin
    # ma'lumotni aniq/izchil holatga keltirish uchun baribir `false`ga
    # backfill qilinadi (`notified`/boshqa bool ustunlar bilan bir xil
    # konvensiya).
    op.execute("UPDATE alerts SET network_response_done = false WHERE network_response_done IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_events', 'device_file_path')
    op.drop_column('alerts', 'network_response_done')
    # ### end Alembic commands ###
