"""add_alert_and_event_performance_indexes

Revision ID: 60a696c5452e
Revises: 79ad4a5404a6
Create Date: 2026-09-16 09:44:59.508491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a696c5452e'
down_revision: Union[str, None] = '79ad4a5404a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # `alerts` production'da hozircha ~10 000 qator - oddiy (transaksion)
    # CREATE INDEX bir necha soniyada tugaydi, yozishlarni bloklashi
    # amaliy jihatdan sezilmaydi.
    op.create_index('ix_alerts_acknowledged', 'alerts', ['acknowledged'], unique=False)
    op.create_index('ix_alerts_device_id_timestamp', 'alerts', ['device_id', 'timestamp'], unique=False)
    op.create_index('ix_alerts_notified', 'alerts', ['notified'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_timestamp', 'alerts', ['timestamp'], unique=False)

    # `events` production'da 7.6 million+ qator (1.2 GB) - oddiy CREATE
    # INDEX butun jadvalni yozish uchun bloklab qo'yadi (parser_engine
    # doimiy yozib turadi). PostgreSQL'da CONCURRENTLY orqali - bu
    # yozishlarni bloklamaydi, lekin tranzaksiya ICHIDA ishlamaydi,
    # shuning uchun `autocommit_block()` orqali Alembic'ning odatiy
    # tranzaksiyasidan chetga chiqariladi. SQLite'da (dev/test, CONCURRENTLY
    # mavjud emas va kerak ham emas - kichik hajm) oddiy yo'l ishlatiladi.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        with op.get_context().autocommit_block():
            op.create_index(
                'ix_events_device_id_timestamp', 'events', ['device_id', 'timestamp'],
                unique=False, postgresql_concurrently=True,
            )
    else:
        op.create_index('ix_events_device_id_timestamp', 'events', ['device_id', 'timestamp'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_device_id_timestamp', table_name='events')
    op.drop_index('ix_alerts_timestamp', table_name='alerts')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_notified', table_name='alerts')
    op.drop_index('ix_alerts_device_id_timestamp', table_name='alerts')
    op.drop_index('ix_alerts_acknowledged', table_name='alerts')
    # ### end Alembic commands ###
