"""add file decisions

Revision ID: 71527755ac21
Revises: 33ec5a1ac904
Create Date: 2026-09-21 00:31:41.723373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71527755ac21'
down_revision: Union[str, None] = '33ec5a1ac904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_decisions_sha256'), 'file_decisions', ['sha256'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_decisions_sha256'), table_name='file_decisions')
    op.drop_table('file_decisions')
    # ### end Alembic commands ###
