"""add_missing_api_tokens_agent_hostname_index

Revision ID: 79ad4a5404a6
Revises: c15ffeb890b8
Create Date: 2026-09-16 08:59:00.507269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ad4a5404a6'
down_revision: Union[str, None] = 'c15ffeb890b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_api_tokens_agent_hostname'), 'api_tokens', ['agent_hostname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_tokens_agent_hostname'), table_name='api_tokens')
    # ### end Alembic commands ###
