"""initial_schema_baseline

Revision ID: c15ffeb890b8
Revises: 
Create Date: 2026-09-16 08:40:24.380694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15ffeb890b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=12), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('agent_hostname', sa.String(length=255), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_api_tokens_agent_hostname'), 'api_tokens', ['agent_hostname'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_index('ix_audit_log_username', 'audit_log', ['username'], unique=False)
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('device_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_ip', sa.String(length=45), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_history_ip', 'device_history', ['device_ip'], unique=False)
    op.create_index('ix_device_history_timestamp', 'device_history', ['timestamp'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('connection_type', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_score_updated_at', sa.DateTime(), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('os_guess', sa.String(length=255), nullable=True),
    sa.Column('open_ports', sa.Text(), nullable=True),
    sa.Column('discovery_source', sa.String(length=50), nullable=True),
    sa.Column('last_discovered_at', sa.DateTime(), nullable=True),
    sa.Column('agent_last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('agent_os', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('file_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=False),
    sa.Column('dest_ip', sa.String(length=45), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('file_ext', sa.String(length=20), nullable=True),
    sa.Column('magic', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('threat_score', sa.Integer(), nullable=True),
    sa.Column('checked_sources', sa.String(length=255), nullable=True),
    sa.Column('stored_path', sa.String(length=1000), nullable=True),
    sa.Column('deep_scanned', sa.Boolean(), nullable=True),
    sa.Column('deep_scan_findings', sa.Text(), nullable=True),
    sa.Column('parent_file_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_file_event_id'], ['file_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_events_checked', 'file_events', ['checked'], unique=False)
    op.create_index('ix_file_events_deep_scanned', 'file_events', ['deep_scanned'], unique=False)
    op.create_index(op.f('ix_file_events_sha256'), 'file_events', ['sha256'], unique=False)
    op.create_table('hash_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('threat_name', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hash_blacklist_sha256'), 'hash_blacklist', ['sha256'], unique=True)
    op.create_table('raw_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_logs_processed', 'raw_logs', ['processed'], unique=False)
    op.create_index('ix_raw_logs_received_at', 'raw_logs', ['received_at'], unique=False)
    op.create_table('topology_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_interface', sa.String(length=100), nullable=True),
    sa.Column('neighbor_chassis_id', sa.String(length=100), nullable=True),
    sa.Column('neighbor_system_name', sa.String(length=255), nullable=True),
    sa.Column('neighbor_port_id', sa.String(length=100), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('auth_source', sa.String(length=20), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('device_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('mean_events_per_hour', sa.Integer(), nullable=True),
    sa.Column('stddev_events_per_hour', sa.Integer(), nullable=True),
    sa.Column('typical_active_hours', sa.String(length=255), nullable=True),
    sa.Column('lookback_days', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('dest_ip', sa.String(length=45), nullable=True),
    sa.Column('dest_domain', sa.String(length=255), nullable=True),
    sa.Column('dest_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('raw_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['raw_log_id'], ['raw_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_dest_ip', 'events', ['dest_ip'], unique=False)
    op.create_index('ix_events_timestamp', 'events', ['timestamp'], unique=False)
    op.create_table('web_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('dest_ip', sa.String(length=45), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('path', sa.String(length=1500), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_web_access_domain_timestamp', 'web_access_logs', ['domain', 'timestamp'], unique=False)
    op.create_index(op.f('ix_web_access_logs_dest_ip'), 'web_access_logs', ['dest_ip'], unique=False)
    op.create_index(op.f('ix_web_access_logs_domain'), 'web_access_logs', ['domain'], unique=False)
    op.create_index(op.f('ix_web_access_logs_source_ip'), 'web_access_logs', ['source_ip'], unique=False)
    op.create_index('ix_web_access_source_ip_timestamp', 'web_access_logs', ['source_ip', 'timestamp'], unique=False)
    op.create_index('ix_web_access_timestamp', 'web_access_logs', ['timestamp'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('file_event_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('mitre_technique_id', sa.String(length=20), nullable=True),
    sa.Column('mitre_technique_name', sa.String(length=255), nullable=True),
    sa.Column('mitre_tactic', sa.String(length=100), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['file_event_id'], ['file_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_index('ix_web_access_timestamp', table_name='web_access_logs')
    op.drop_index('ix_web_access_source_ip_timestamp', table_name='web_access_logs')
    op.drop_index(op.f('ix_web_access_logs_source_ip'), table_name='web_access_logs')
    op.drop_index(op.f('ix_web_access_logs_domain'), table_name='web_access_logs')
    op.drop_index(op.f('ix_web_access_logs_dest_ip'), table_name='web_access_logs')
    op.drop_index('ix_web_access_domain_timestamp', table_name='web_access_logs')
    op.drop_table('web_access_logs')
    op.drop_index('ix_events_timestamp', table_name='events')
    op.drop_index('ix_events_dest_ip', table_name='events')
    op.drop_table('events')
    op.drop_table('device_baselines')
    op.drop_table('whitelist')
    op.drop_table('users')
    op.drop_table('topology_links')
    op.drop_index('ix_raw_logs_received_at', table_name='raw_logs')
    op.drop_index('ix_raw_logs_processed', table_name='raw_logs')
    op.drop_table('raw_logs')
    op.drop_index(op.f('ix_hash_blacklist_sha256'), table_name='hash_blacklist')
    op.drop_table('hash_blacklist')
    op.drop_index(op.f('ix_file_events_sha256'), table_name='file_events')
    op.drop_index('ix_file_events_deep_scanned', table_name='file_events')
    op.drop_index('ix_file_events_checked', table_name='file_events')
    op.drop_table('file_events')
    op.drop_table('devices')
    op.drop_index('ix_device_history_timestamp', table_name='device_history')
    op.drop_index('ix_device_history_ip', table_name='device_history')
    op.drop_table('device_history')
    op.drop_table('blacklist')
    op.drop_index('ix_audit_log_username', table_name='audit_log')
    op.drop_index('ix_audit_log_timestamp', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_api_tokens_agent_hostname'), table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
